version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: bil-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://localhost:27017/bilDB
    depends_on:
      - mongo
