apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: umutaa/kube_eksamen-frontend:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mongo-config
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec: 
  selector:
    app: frontend
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
    