name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout koden
      uses: actions/checkout@v3

    - name: Login til DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mit-projekt:latest .

    - name: Push image til DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mit-projekt:latest
