name: Build Only

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v3

    - name: Byg Docker image
      run: |
        docker build -t my-app:latest .
